[1m[36mread_data***********************************************************************
[1m[34m* dev1.group_1 ** changed : True ***********************************************
[1m[32m---- echo_task ** changed : False ---------------------------------------------- CRITICAL
Hello from CRITICAL
[1m[33m^^^^ END read_data ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1m[34m* dev2.group_1 ** changed : False **********************************************
[1m[32m---- echo_task ** changed : False ---------------------------------------------- CRITICAL
Hello from CRITICAL
[1m[32m^^^^ END read_data ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1m[34m* dev3.group_2 ** changed : False **********************************************
[1m[31mvvvv read_data ** changed : False vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv ERROR
Traceback (most recent call last):
  File "/Users/patrick/src/brigade/brigade/core/task.py", line 61, in start
    r = self.task(self, **self.params)
  File "/Users/patrick/src/brigade/tests/plugins/functions/text/test_print_result.py", line 29, in read_data
    severity_level=logging.WARN,
  File "/Users/patrick/src/brigade/brigade/core/task.py", line 98, in run
    raise r.exception
  File "/Users/patrick/src/brigade/brigade/core/task.py", line 61, in start
    r = self.task(self, **self.params)
  File "/Users/patrick/src/brigade/brigade/plugins/tasks/data/load_yaml.py", line 19, in load_yaml
    data = yaml.load(f.read())
  File "/Users/patrick/src/brigade/.tox/py36/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/Users/patrick/src/brigade/.tox/py36/lib/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/Users/patrick/src/brigade/.tox/py36/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/patrick/src/brigade/.tox/py36/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/patrick/src/brigade/.tox/py36/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/patrick/src/brigade/.tox/py36/lib/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/Users/patrick/src/brigade/.tox/py36/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/patrick/src/brigade/.tox/py36/lib/python3.6/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/Users/patrick/src/brigade/.tox/py36/lib/python3.6/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/Users/patrick/src/brigade/.tox/py36/lib/python3.6/site-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/Users/patrick/src/brigade/.tox/py36/lib/python3.6/site-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 7, column 1:
    is_it_broken; "You bet!"
    ^
could not find expected ':'
  in "<unicode string>", line 8, column 1:
    changed: True
    ^

[1m[32m---- echo_task ** changed : False ---------------------------------------------- CRITICAL
Hello from CRITICAL
[1m[31m^^^^ END read_data ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1m[34m* dev4.group_2 ** changed : False **********************************************
[1m[32m---- echo_task ** changed : False ---------------------------------------------- CRITICAL
Hello from CRITICAL
[1m[32m^^^^ END read_data ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
